on:
  push:
    branches:
      - "*"
name: Artifact test  
jobs:
  fileUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to slack step
        if: always()
        uses: adrey/slack-file-upload-action@master
        with:
          token: xoxb-890217535927-4471073842273-mwUTHU6r3Kto8sNdsrR0Dl2Z
          path: package.json
          channel: test
